INSERT INTO classifier(id, fk_parent, name) VALUES( 1000, null, 'Kõik kategooriad');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1718, null, 'Tartu kunstioksjon');
INSERT INTO classifier(id, fk_parent, name) VALUES(  713, null, 'Heategevus');
INSERT INTO classifier(id, fk_parent, name) VALUES(  749, null, 'Pankrotivara');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1001, null, 'Riigivara ja ettevõtted');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1536, null, 'Antiikesemed ja kunst');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1434, null, 'Arvutid');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1419, null, 'Audio/video');
INSERT INTO classifier(id, fk_parent, name) VALUES(  938, null, 'Auto/moto');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1389, null, 'Ehitusmaterjalid');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1138, null, 'Ehted ja väärisesemed');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1514, null, 'Harrastused ja vaba aeg');
INSERT INTO classifier(id, fk_parent, name) VALUES(  170, null, 'Ilu ja tervis');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1265, null, 'Kellad');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1370, null, 'Kinnisvara');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1484, null, 'Kodu');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1448, null, 'Kodumasinad');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1191, null, 'Kollektsioneerimine');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1201, null, 'Kontori- ja äritarbed');
INSERT INTO classifier(id, fk_parent, name) VALUES(  771, null, 'Koolikaubad');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1503, null, 'Lastekaubad');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1496, null, 'Lemmikloomad');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1411, null, 'Põllumajandus');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1530, null, 'Raamatud, ajalehed');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1506, null, 'Riided ja jalatsid');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1443, null, 'Telefonid');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1475, null, 'Töö ja koolitus');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1397, null, 'Tööriistad ja masinad');
INSERT INTO classifier(id, fk_parent, name) VALUES(    2, null, 'Varia');
INSERT INTO classifier(id, fk_parent, name) VALUES( 1456, null, 'Äri ja teenused');
INSERT INTO classifier(id, fk_parent, name) VALUES(   21, null, 'XXX');
